---
title: "IMT 573: Assignment Instructions"
author: "Emma S. Spiro"
date: 'Last Updated: June 15, 2021'
output: html_document
---

Before beginning any assignment, please ensure you have access to R and RStudio; this can be on your own personal computer or on the IMT 573 R Studio Cloud. Assignments will be written assuming you will be using RStudio Cloud. Please reach out to your instructional team if questions arise. 

### Instructions

1. Review the IMT 573 Code of Conduct. 

2. Find the appropriate assignment on RStudio Cloud. Each assignment will be its own project in RStudio. In each project, you will find all  necessary files, data, etc. needed to complete the assignment. 

3. Before starting, click on the `Knit` button (above) to ensure you are starting with an assignment template that knits to a data science report in PDF form. Bring any issues to your instructors as soon as possible.

4. Supply your solutions to the assignment by editing the RMarkdown document directly. You will add code and written responses there. 

3. Replace the "YOUR NAME HERE" text in the `author:` field with your own full name. Any collaborators must be listed on the top of your assignment. 

4. Be sure to include well-documented (e.g. commented) code chucks, figures, and clearly written text chunk explanations as necessary. Any figures should be clearly labeled and appropriately referenced within the text. Be sure that each visualization adds value to your written explanation; avoid redundancy -- you do no need four different visualizations of the same pattern.

4.  Collaboration on problem sets is fun and useful, and we encourage it, but each student must turn in an individual write-up in their own words as well as code/work that is their own.  Regardless of whether you work with others, what you turn in must be your own work; this includes code and interpretation of results. The names of all collaborators must be listed on each assignment. Do not copy-and-paste from other students' responses or code.

5. All materials and resources that you use (with the exception of lecture slides) must be appropriately referenced within your assignment.  

6. Remember partial credit will be awarded for each question for which a serious attempt at finding an answer has been shown. Students are \emph{strongly} encouraged to attempt each question and to document their reasoning process even if they cannot find the correct answer. If you would like to include R code to show this process, but it does not run without errors you can do so with the `eval=FALSE` option as follows:

```{r example chunk with a bug, eval=FALSE}
a + b # these object don't exist 
# if you run this on its own it with give an error
```

7. When you have completed the assignment, click on the `Knit` button again. Once you have **checked** that your code both runs in the Console and knits correctly when you click `Knit`, download and rename the knitted PDF file to `psX_YourLastName_YourFirstName.pdf`, and submit the PDF file on Canvas.

